weights: ../weights/yolov4-csp.pth
cfg: models/yolov4-csp.yaml
data: data/adtp.yaml
hyp: data/hyp.finetune.yaml
epochs: 5
batch_size: 6
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
name: ''
device: '0'
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
logdir: runs/
total_batch_size: 6
world_size: 1
global_rank: -1
